services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: karan@123
      MYSQL_DATABASE: crud_app
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  backend:
    build: ./api
    container_name: backend-api
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: karan@123
      DB_NAME: crud_app
      JWT_SECRET: devopsShackSuperSecretKey
      RESET_ADMIN_PASS: 'true'
    ports:
      - 5000:5000

  frontend: 
    build: ./client
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 3000:80

volumes:
  mysql_data:

