apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: devshakops
spec:
  selector:
    app: backend
  ports:
  - name: backend-api
    port: 5000
    targetPort: 5000
  type: ClusterIP
