apiVersion: apps/v1
kind: Deployment
metadata:
  name: devshakops-backend
  namespace: devshakops
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: deploykarle/devshakops:backend
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: devshakops-configs
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: devshakops-configs
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: devshakops-configs
              key: DB_NAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devshakops-secret
              key: DB_PASSWORD
